In [1]:
import os

current_directory = os.getcwd()
print("Current Working Directory:", current_directory)

Current Working Directory: /kaggle/working

In [2]:
import pandas as pd
df_train = pd.read_csv('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Dataset_for_AQI_Classification/Dataset_for_AQI_Classification/train_data.csv')
df_train

,Location,Filename,Year,Month,Day,Hour,AQI,PM2.5,PM10,O3,CO,SO2,NO2,AQI_Class
0,Tamil Nadu,TN_UnFSG_2023-03-02-08.30-1.jpg,2023,3,2,8:30,119,69.00,106.00,8.00,358.00,22.00,26.00,c_Unhealthy_for_Sensitive_Groups
1,Bengaluru,BENGR_Mod_2023-02-24-08.30-1-166.jpg,2023,2,24,8:30,68,32.00,61.00,26.00,228.00,5.00,21.00,b_Moderate
2,"Biratnagar, Nepal",BIR_UNFSG_VF_2023-02-03-15.00-2-24.jpg,2023,2,3,15:00,141,47.96,68.92,65.57,0.41,2.80,2.51,c_Unhealthy_for_Sensitive_Groups
3,Mumbai,MH_UnFSG_2023-03-10-16.00-1-76.jpg,2023,3,10,16:00,141,72.00,108.00,NaN,NaN,NaN,63.00,c_Unhealthy_for_Sensitive_Groups
4,"ITO, Delhi",DEL_SEV_2023-02-07-14.00-2-8.jpg,2023,2,7,14:00,449,337.00,198.00,23.00,24.00,13.00,57.00,f_Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7828,"Biratnagar, Nepal",BRI_Un_2023-02-09-08.00-1.jpg,2023,2,9,8:00,171,112.46,163.45,31.17,0.96,3.84,18.78,d_Unhealthy
7829,"ITO, Delhi",DEL_SEV_2023-02-17-13.00-2-25.jpg,2023,2,17,13:00,372,348.00,199.00,25.00,67.00,10.00,107.00,f_Severe
7830,"New Ind Town, Faridabad",HAR_VUN_2022-10-02-10.00-1-1489.jpg,2022,10,2,10:00,230,185.00,199.00,10.00,52.00,12.00,26.00,e_Very_Unhealthy
7831,Mumbai,MH_UnFSG_2023-03-14-13.00-1-385.jpg,2023,3,14,13:00,138,90.00,120.00,143.00,21.00,9.00,16.00,c_Unhealthy_for_Sensitive_Groups
7832,Mumbai,MH_UH_2023-02-11-03.30-2-41.jpg,2023,2,11,15:30,154,66.20,93.75,91.00,20.00,NaN,98.00,d_Unhealthy

In [3]:
df_val = pd.read_csv('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Dataset_for_AQI_Classification/Dataset_for_AQI_Classification/val_data.csv')
df_val

,Location,Filename,Year,Month,Day,Hour,AQI,PM2.5,PM10,O3,CO,SO2,NO2,AQI_Class
0,Bengaluru,BENGR_Mod_2023-02-23-08.30-1-401.jpg,2023,2,23,8:30,97,43.00,78.00,26.00,258.00,10.00,17.00,b_Moderate
1,"ITO, Delhi",DEL_SEV_2023-02-22-14.00-2-221.jpg,2023,2,22,14:00,450,500.00,480.00,91.00,78.00,17.00,47.00,f_Severe
2,"New Ind Town, Faridabad",HAR_VUN_2022-10-02-10.00-1-2361.jpg,2022,10,2,10:00,230,185.00,199.00,10.00,52.00,12.00,26.00,e_Very_Unhealthy
3,"ITO, Delhi",DEL_VUnH_2023-02-16-14.00-2-7.jpg,2023,2,16,14:00,268,401.00,325.00,73.00,88.00,16.00,NaN,e_Very_Unhealthy
4,Mumbai,MH_Good_2023-03-23-17.00-2.jpg,2023,3,23,17:00,47,14.00,41.00,35.00,6.00,5.00,7.00,a_Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,"ITO, Delhi",DEL_SEV_2023-02-07-14.00-1-103.jpg,2023,2,7,14:00,449,337.00,198.00,23.00,24.00,13.00,57.00,f_Severe
1955,"ITO, Delhi",DEL_SEV_2023-02-20-14.00-2-156.jpg,2023,2,20,14:00,363,257.00,139.00,41.00,65.00,35.00,83.00,f_Severe
1956,"ITO, Delhi",DEL_SEV_2023-02-22-14.00-2-96.jpg,2023,2,22,14:00,450,500.00,480.00,91.00,78.00,17.00,47.00,f_Severe
1957,"Biratnagar, Nepal",BIR_UNH_VF_2023-02-02- 1700-3-72.jpg,2023,2,2,17:00,156,67.06,95.93,52.38,0.52,3.35,6.49,d_Unhealthy
1958,Mumbai,MH_UN_2023-03-15-15.00-1-15.jpg,2023,3,15,15:00,162,193.00,466.00,225.00,39.00,8.00,61.00,d_Unhealthy

In [4]:
df_test = pd.read_csv('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Dataset_for_AQI_Classification/Dataset_for_AQI_Classification/testing_data.csv')
df_test = df_test.sample(frac=1).reset_index(drop=True)
df_test

,Location,Filename,Year,Month,Day,Hour,AQI,PM2.5,PM10,O3,CO,SO2,NO2,AQI_Class
0,Mumbai,MH_UnFSG_2023-02-23-11.00-1-26.jpg,2023,2,23,11:00,130,319.00,201.00,54.00,76.00,NaN,169.00,c_Unhealthy_for_Sensitive_Groups
1,Mumbai,MH_Good_2023-03-22-18.00-1-391.jpg,2023,3,22,18:00,47,21.00,43.00,37.00,4.00,8.0,7.00,a_Good
2,Mumbai,MH_UnFSG_2023-03-18-11.00-1-197.jpg,2023,3,18,11:00,114,143.00,114.00,73.00,1.00,7.0,87.00,c_Unhealthy_for_Sensitive_Groups
3,"New Ind Town, Faridabad",HAR_VUN_2022-10-02-10.00-1-761.jpg,2022,10,2,10:00,230,185.00,199.00,10.00,52.00,12.0,26.00,e_Very_Unhealthy
4,"Biratnagar, Nepal",BIR_UNFSG_VF_2023-02-03-15.00-2-16.jpg,2023,2,3,15:00,141,47.96,68.92,65.57,0.41,2.8,2.51,c_Unhealthy_for_Sensitive_Groups
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2443,Bengaluru,BENGR_Mod_2023-03-06-08.30-1-591.jpg,2023,3,6,8:30,68,36.00,59.00,22.00,171.00,5.0,14.00,b_Moderate
2444,Mumbai,MH_UnFSG_2023-03-08-11.00-1-71.jpg,2023,3,8,11:00,124,287.00,177.00,NaN,NaN,NaN,85.00,c_Unhealthy_for_Sensitive_Groups
2445,"Knowledge park, Greater Noida",UP_VUN_2023-02-27-10.30-1-85.jpg,2023,2,27,10:30,299,329.00,299.00,2.00,20.00,48.0,27.00,e_Very_Unhealthy
2446,Mumbai,MH_UH_2023-02-18-11.00-1-16.jpg,2023,2,18,11:00,151,277.00,166.00,41.00,24.00,NaN,NaN,d_Unhealthy
2447,Tamil Nadu,TN_UN_2023-03-11-08.00-1-246.jpg,2023,3,11,8:00,152,102.00,162.00,16.00,252.00,26.0,32.00,d_Unhealthy

In [5]:
#Import all necessary library
import sys
import numpy as np

from typing import Dict, Optional, Tuple
from pathlib import Path

import math
import pandas as pd

import tensorflow as tf
from tensorflow import keras

import seaborn as sns
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from tensorflow.keras import backend #Keras version 2.1.6
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Concatenate, LeakyReLU, Input, Conv2D, MaxPooling2D, BatchNormalization, Add 

from tensorflow.keras import layers

from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.preprocessing import image
#from PIL import Image

from sklearn.metrics import r2_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix


%matplotlib inline

In [6]:
#Preparing label data for Training
y_train = df_train[['AQI','PM2.5','PM10','O3','CO','SO2','NO2']].copy()
y_train

      AQI   PM2.5    PM10      O3      CO    SO2     NO2
0     119   69.00  106.00    8.00  358.00  22.00   26.00
1      68   32.00   61.00   26.00  228.00   5.00   21.00
2     141   47.96   68.92   65.57    0.41   2.80    2.51
3     141   72.00  108.00     NaN     NaN    NaN   63.00
4     449  337.00  198.00   23.00   24.00  13.00   57.00
...   ...     ...     ...     ...     ...    ...     ...
7828  171  112.46  163.45   31.17    0.96   3.84   18.78
7829  372  348.00  199.00   25.00   67.00  10.00  107.00
7830  230  185.00  199.00   10.00   52.00  12.00   26.00
7831  138   90.00  120.00  143.00   21.00   9.00   16.00
7832  154   66.20   93.75   91.00   20.00    NaN   98.00

[7833 rows x 7 columns]

In [7]:
# Check missing data
print(y_train.isna().sum())

# Interpolation
y_train = y_train.interpolate(method='linear', limit_direction='forward', axis=0)

AQI        0
PM2.5      0
PM10       0
O3       187
CO       357
SO2      936
NO2      273
dtype: int64

In [8]:
# Check data
print(y_train.isna().sum())

AQI      0
PM2.5    0
PM10     0
O3       0
CO       0
SO2      0
NO2      0
dtype: int64

In [9]:
# Preparing label data for Validation
y_val = df_val[['AQI','PM2.5','PM10','O3','CO','SO2','NO2']].copy()
y_val

      AQI   PM2.5    PM10      O3      CO    SO2    NO2
0      97   43.00   78.00   26.00  258.00  10.00  17.00
1     450  500.00  480.00   91.00   78.00  17.00  47.00
2     230  185.00  199.00   10.00   52.00  12.00  26.00
3     268  401.00  325.00   73.00   88.00  16.00    NaN
4      47   14.00   41.00   35.00    6.00   5.00   7.00
...   ...     ...     ...     ...     ...    ...    ...
1954  449  337.00  198.00   23.00   24.00  13.00  57.00
1955  363  257.00  139.00   41.00   65.00  35.00  83.00
1956  450  500.00  480.00   91.00   78.00  17.00  47.00
1957  156   67.06   95.93   52.38    0.52   3.35   6.49
1958  162  193.00  466.00  225.00   39.00   8.00  61.00

[1959 rows x 7 columns]

In [10]:
# Check missing data
print(y_val.isna().sum())

# Interpolation
y_val = y_val.interpolate(method='linear', limit_direction='forward', axis=0)

AQI        0
PM2.5      0
PM10       0
O3        53
CO       108
SO2      237
NO2       77
dtype: int64

In [11]:
# Check data
print(y_val.isna().sum())

AQI      0
PM2.5    0
PM10     0
O3       0
CO       0
SO2      0
NO2      0
dtype: int64

In [12]:
# Preparing label data for Testing
y_test = df_test[['AQI','PM2.5','PM10','O3','CO','SO2','NO2']].copy()
y_test

      AQI   PM2.5    PM10     O3      CO   SO2     NO2
0     130  319.00  201.00  54.00   76.00   NaN  169.00
1      47   21.00   43.00  37.00    4.00   8.0    7.00
2     114  143.00  114.00  73.00    1.00   7.0   87.00
3     230  185.00  199.00  10.00   52.00  12.0   26.00
4     141   47.96   68.92  65.57    0.41   2.8    2.51
...   ...     ...     ...    ...     ...   ...     ...
2443   68   36.00   59.00  22.00  171.00   5.0   14.00
2444  124  287.00  177.00    NaN     NaN   NaN   85.00
2445  299  329.00  299.00   2.00   20.00  48.0   27.00
2446  151  277.00  166.00  41.00   24.00   NaN     NaN
2447  152  102.00  162.00  16.00  252.00  26.0   32.00

[2448 rows x 7 columns]

In [13]:
# Check missing data
print(y_test.isna().sum())

# Interpolation
y_test = y_test.interpolate(method='linear', limit_direction='forward', axis=0)

AQI        0
PM2.5      0
PM10       0
O3        63
CO       117
SO2      311
NO2       88
dtype: int64

In [14]:
# Check data
print(y_test.isna().sum())

AQI      0
PM2.5    0
PM10     0
O3       0
CO       0
SO2      1
NO2      0
dtype: int64

In [15]:
# Takes the path to an RGB image file as input, reads the image using Keras library and converts it to a NumPy array. 

def build_x(path, y, df):
    train_img = []
    for i in range(len(y)):
        img = image.load_img(path + df['Filename'][i])
        img = image.img_to_array(img)
        img = img / 255
        train_img.append(img)

    x = np.array(train_img)
    return x

In [16]:
train_img = build_x('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Air Pollution Image Dataset/Air Pollution Image Dataset/Combined_Dataset/All_img/',y_train, df_train)
train_img.shape

(7833, 224, 224, 3)

In [17]:
val_img = build_x('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Air Pollution Image Dataset/Air Pollution Image Dataset/Combined_Dataset/All_img/',y_val, df_val)
val_img.shape

(1959, 224, 224, 3)

In [18]:
test_img = build_x('/kaggle/input/air-pollution-image-dataset-from-india-and-nepal/Air Pollution Image Dataset/Air Pollution Image Dataset/Combined_Dataset/All_img/',y_test, df_test)
test_img.shape

(2448, 224, 224, 3)

In [19]:
#from tensorflow.keras.models import Model
#from tensorflow.keras.layers import Input, Conv2D, LeakyReLU, MaxPooling2D, Flatten, Dense, Add

# Define input
inputs = Input(shape=(224, 224, 3))

# Convolution Layer
conv1 = Conv2D(64, (3, 3), padding='same', name='block1_conv1')(inputs)
leak1 = LeakyReLU(alpha=0.1)(conv1)
conv2 = Conv2D(64, (3, 3), padding='same', name='block1_conv2')(leak1)
leak2 = LeakyReLU(alpha=0.1)(conv2)
pool1 = MaxPooling2D((3, 3), strides=(2, 2), name='block1_pool')(leak2)

conv3 = Conv2D(128, (3, 3), padding='same', name='block2_conv1')(pool1)
leak3 = LeakyReLU(alpha=0.1)(conv3)
conv4 = Conv2D(128, (3, 3), padding='same', name='block2_conv2')(leak3)
leak4 = LeakyReLU(alpha=0.1)(conv4)
pool2 = MaxPooling2D((3, 3), strides=(2, 2), name='block2_pool')(leak4)

conv5 = Conv2D(128, (3, 3), padding='same', name='block3_conv1')(pool2)
leak5 = LeakyReLU(alpha=0.1)(conv5)
res2 = Add()([leak5, pool2])
pool3 = MaxPooling2D((3, 3), strides=(2, 2), name='block3_pool')(res2)

conv7 = Conv2D(128, (3, 3), padding='same', name='block4_conv1')(pool3)
leak7 = LeakyReLU(alpha=0.1)(conv7)
res3 = Add()([leak7, pool3])
pool4 = MaxPooling2D((3, 3), strides=(2, 2), name='block4_pool')(res3)

conv9 = Conv2D(128, (3, 3), padding='same', name='block5_conv1')(pool4)
leak9 = LeakyReLU(alpha=0.1)(conv9)
res4 = Add()([leak9, pool4])
pool5 = MaxPooling2D((3, 3), strides=(2, 2), name='block5_pool')(res4)

conv11 = Conv2D(256, (3, 3), padding='same', name='block6_conv1')(pool5)
leak11 = LeakyReLU(alpha=0.1)(conv11)
conv12 = Conv2D(256, (3, 3), padding='same', name='block6_conv2')(leak11)
leak12 = LeakyReLU(alpha=0.1)(conv12)
pool6 = MaxPooling2D((3, 3), strides=(2, 2), name='block6_pool')(leak12)

# Flatten Layer
flatten = Flatten()(pool6)

# Fully Connected Layer
dense1 = Dense(1024, activation='relu')(flatten)
dense2 = Dense(1024, activation='relu')(dense1)

# Output Layer
pm25_output = Dense(1, activation='linear', name='PM2.5_output')(dense2)
pm10_output = Dense(1, activation='linear', name='PM10_output')(dense2)
o3_output = Dense(1, activation='linear', name='O3_output')(dense2)
co_output = Dense(1, activation='linear', name='CO_output')(dense2)
so2_output = Dense(1, activation='linear', name='SO2_output')(dense2)
no2_output = Dense(1, activation='linear', name='NO2_output')(dense2)

# Define model
model = Model(inputs=inputs, outputs=[pm25_output, pm10_output, o3_output, co_output, so2_output, no2_output])

optimizer = Adam(learning_rate=1e-4, clipnorm=1.0)  # 使用clipnorm或clipvalue限制梯度大小
#model.compile(optimizer=optimizer, loss='mae')
# Compile model
model.compile(optimizer=optimizer, loss='mae')
model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block1_conv1        │ (None, 224, 224,  │      1,792 │ input_layer[0][0] │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu         │ (None, 224, 224,  │          0 │ block1_conv1[0][… │
│ (LeakyReLU)         │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block1_conv2        │ (None, 224, 224,  │     36,928 │ leaky_re_lu[0][0] │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_1       │ (None, 224, 224,  │          0 │ block1_conv2[0][… │
│ (LeakyReLU)         │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block1_pool         │ (None, 111, 111,  │          0 │ leaky_re_lu_1[0]… │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block2_conv1        │ (None, 111, 111,  │     73,856 │ block1_pool[0][0] │
│ (Conv2D)            │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_2       │ (None, 111, 111,  │          0 │ block2_conv1[0][… │
│ (LeakyReLU)         │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block2_conv2        │ (None, 111, 111,  │    147,584 │ leaky_re_lu_2[0]… │
│ (Conv2D)            │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_3       │ (None, 111, 111,  │          0 │ block2_conv2[0][… │
│ (LeakyReLU)         │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block2_pool         │ (None, 55, 55,    │          0 │ leaky_re_lu_3[0]… │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block3_conv1        │ (None, 55, 55,    │    147,584 │ block2_pool[0][0] │
│ (Conv2D)            │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_4       │ (None, 55, 55,    │          0 │ block3_conv1[0][… │
│ (LeakyReLU)         │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 55, 55,    │          0 │ leaky_re_lu_4[0]… │
│                     │ 128)              │            │ block2_pool[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block3_pool         │ (None, 27, 27,    │          0 │ add[0][0]         │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block4_conv1        │ (None, 27, 27,    │    147,584 │ block3_pool[0][0] │
│ (Conv2D)            │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_5       │ (None, 27, 27,    │          0 │ block4_conv1[0][… │
│ (LeakyReLU)         │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 27, 27,    │          0 │ leaky_re_lu_5[0]… │
│                     │ 128)              │            │ block3_pool[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block4_pool         │ (None, 13, 13,    │          0 │ add_1[0][0]       │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block5_conv1        │ (None, 13, 13,    │    147,584 │ block4_pool[0][0] │
│ (Conv2D)            │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_6       │ (None, 13, 13,    │          0 │ block5_conv1[0][… │
│ (LeakyReLU)         │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_2 (Add)         │ (None, 13, 13,    │          0 │ leaky_re_lu_6[0]… │
│                     │ 128)              │            │ block4_pool[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block5_pool         │ (None, 6, 6, 128) │          0 │ add_2[0][0]       │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block6_conv1        │ (None, 6, 6, 256) │    295,168 │ block5_pool[0][0] │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_7       │ (None, 6, 6, 256) │          0 │ block6_conv1[0][… │
│ (LeakyReLU)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block6_conv2        │ (None, 6, 6, 256) │    590,080 │ leaky_re_lu_7[0]… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ leaky_re_lu_8       │ (None, 6, 6, 256) │          0 │ block6_conv2[0][… │
│ (LeakyReLU)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block6_pool         │ (None, 2, 2, 256) │          0 │ leaky_re_lu_8[0]… │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1024)      │          0 │ block6_pool[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 1024)      │  1,049,600 │ flatten[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1024)      │  1,049,600 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ PM2.5_output        │ (None, 1)         │      1,025 │ dense_1[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ PM10_output (Dense) │ (None, 1)         │      1,025 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ O3_output (Dense)   │ (None, 1)         │      1,025 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ CO_output (Dense)   │ (None, 1)         │      1,025 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ SO2_output (Dense)  │ (None, 1)         │      1,025 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ NO2_output (Dense)  │ (None, 1)         │      1,025 │ dense_1[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 3,693,510 (14.09 MB)

 Trainable params: 3,693,510 (14.09 MB)

 Non-trainable params: 0 (0.00 B)

In [20]:
#from tensorflow.keras.callbacks import ModelCheckpoint
from glob import glob
from tensorflow.keras.callbacks import ReduceLROnPlateau

# Weight
saved_weights_dir = "/kaggle/input/air-weight-41/"
saved_weights = sorted(glob(os.path.join(saved_weights_dir, "model_weights_epoch_*.weights.h5")))

if saved_weights:
    latest_weights = saved_weights[-1]
    print(f"加載權重：{latest_weights}")
    model.load_weights(latest_weights)
    initial_epoch = int(latest_weights.split('_')[-1].split('.')[0])  # 獲取初始epoch
else:
    print("沒有找到已保存的權重，從頭開始訓練")
    initial_epoch = 0

# Path of weight
weight_path = "model_weights_epoch_{epoch:03d}.weights.h5"

# Callback Function
callbacks = [
    ModelCheckpoint(filepath=weight_path, 
                    monitor='val_loss',        
                    save_weights_only=True,    # Store weight
                    save_freq='epoch',         # Each epoch
                    verbose=1,                 # Show progress
                    save_best_only=False)      # Store each file
]

lr_callback = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1)
callbacks.append(lr_callback)

加載權重：/kaggle/input/air-weight-41/model_weights_epoch_041.weights.h5

/opt/conda/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:415: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 70 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
history = model.fit(
    train_img, 
    [y_train['PM2.5'], y_train['PM10'], y_train['O3'], y_train['CO'], y_train['SO2'], y_train['NO2']],
    validation_data=(val_img, [y_val['PM2.5'], y_val['PM10'], y_val['O3'], y_val['CO'], y_val['SO2'], y_val['NO2']]),
    batch_size=16, 
    epochs=100, 
    initial_epoch=initial_epoch,
    callbacks=callbacks
)

Epoch 42/100
 24/490 ━━━━━━━━━━━━━━━━━━━━ 52:13 7s/step - loss: 20.8660

In [ ]:
model.save('/kaggle/working/pm2.5_v2.h5')